language: java
install: mvn clean install -B -V -Dintegration-tests=true
script:
  - cd cloudsim-plus && mvn versioneye:update; cd ..
  - cd cloudsim-plus && mvn clean test -Dintegration-tests=true jacoco:report; cd ..
cache:
  directories:
  - $HOME/.m2
jdk:
  - oraclejdk8 
after_script:
    - cd cloudsim-plus && mvn jacoco:report; cd ..
    - curl http://www.jpm4j.org/install/script -k > jpmInstall.sh
    - sudo sh jpmInstall.sh
    - sudo jpm install com.codacy:codacy-coverage-reporter:assembly
    #Upload the coverage report to codacy.com. It requires the CODACY_PROJECT_TOKEN environment variable
    - codacy-coverage-reporter -l Java -r cloudsim-plus/target/site/jacoco/jacoco.xml
